# Generated by Django 3.0.7 on 2020-06-28 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_student_interests'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='interests',
            field=models.ManyToManyField(related_name='interested_students', to='api.Subject'),
        ),
    ]
